"""decision relation game

Revision ID: 49fe6b55fd05
Revises: 594ab4947077
Create Date: 2019-09-28 23:55:49.261456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49fe6b55fd05'
down_revision = '594ab4947077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier', sa.String(length=140), nullable=True),
    sa.Column('workers', sa.Integer(), nullable=True),
    sa.Column('gameid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gameid'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision1')
    # ### end Alembic commands ###
