"""result1 table and page

Revision ID: 5dcbdfb1b4ee
Revises: 49fe6b55fd05
Create Date: 2019-10-21 01:11:16.665868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dcbdfb1b4ee'
down_revision = '49fe6b55fd05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('sales', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('penalty', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('salvage', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('procure', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('manage', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('gameid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gameid'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result1')
    # ### end Alembic commands ###
