"""game time ps state

Revision ID: 603e4def37ae
Revises: be58e854b159
Create Date: 2019-10-26 11:45:00.046144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603e4def37ae'
down_revision = 'be58e854b159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ps', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('start_time')
        batch_op.drop_column('ps')
        batch_op.drop_column('last_time')

    # ### end Alembic commands ###
