"""decison1 change3!

Revision ID: be58e854b159
Revises: 5dcbdfb1b4ee
Create Date: 2019-10-21 11:38:03.204218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be58e854b159'
down_revision = '5dcbdfb1b4ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision1', schema=None) as batch_op:
        batch_op.drop_column('supplier')
        batch_op.drop_column('workers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workers', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('supplier', sa.VARCHAR(length=140), nullable=True))

    # ### end Alembic commands ###
